/* automatically generated from xfce-firejail-widget.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce_firejail_widget_ui)
#endif
#ifdef __GNUC__
static const char xfce_firejail_widget_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce_firejail_widget_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkAdjustment\" id=\"filesystem_"
  "security_adjustment\"><property name=\"upper\">5</property><property na"
  "me=\"step_increment\">1</property><property name=\"page_increment\">5</"
  "property><property name=\"page_size\">1</property></object><object clas"
  "s=\"XfceTitledDialog\" id=\"firejail_settings_advanced\"><property name"
  "=\"can_focus\">False</property><property name=\"title\" translatable=\""
  "yes\">Advanced Security Settings</property><property name=\"default_wid"
  "th\">550</property><property name=\"default_height\">600</property><pro"
  "perty name=\"icon_name\">firejail-protect</property><property name=\"ty"
  "pe_hint\">normal</property><property name=\"subtitle\" translatable=\"y"
  "es\">Configure how Firejail runs your application in a sandbox</propert"
  "y><child internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-"
  "vbox1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"spacing\">2</property><child i"
  "nternal-child=\"action_area\"><object class=\"GtkHButtonBox\" id=\"dial"
  "og-action_area1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"layout_style\">start"
  "</property><child><object class=\"GtkButton\" id=\"close-button\"><prop"
  "erty name=\"label\">gtk-apply</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"use_stock\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty><property name=\"secondary\">True</property></packing></child><chi"
  "ld><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">"
  "gtk-cancel</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"use_stock\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"pack_type\">end</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkVBox\" id=\"vbox2\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkFrame\" id=\"frame_other"
  "1\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment1\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"border_width\""
  ">6</property><property name=\"bottom_padding\">6</property><property na"
  "me=\"left_padding\">12</property><child><object class=\"GtkCheckButton\""
  " id=\"firejail_settings_run1\"><property name=\"label\" translatable=\""
  "yes\">Run in a Firejail sandbox</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t></child></object></child><child type=\"label\"><object class=\"GtkLab"
  "el\" id=\"label2\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">&lt;b&gt;General&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property></object></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">0</property></packing></child><child><object cla"
  "ss=\"GtkFrame\" id=\"frame_net\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "_xalign\">0</property><property name=\"shadow_type\">none</property><ch"
  "ild><object class=\"GtkAlignment\" id=\"alignment3\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"border_width\">6</property><property name=\"bottom_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkCheckButton\" id=\"enabl"
  "e_network_check\"><property name=\"label\" translatable=\"yes\">_Enable"
  " network</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"active\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkCheckButton\" id=\"n"
  "et_auto_check\"><property name=\"label\" translatable=\"yes\">Fine-tune"
  "d _network control (can reduce performance)</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"active\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child><child><obj"
  "ect class=\"GtkAlignment\" id=\"alignment_net_auto_check\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"bottom_padding\">6</property><property name=\"left"
  "_padding\">12</property><child><object class=\"GtkVBox\" id=\"vbox3\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkTable\" id=\"table1\"><property name=\"visible\">True</propert"
  "y><property name=\"sensitive\">False</property><property name=\"can_foc"
  "us\">False</property><property name=\"n_rows\">2</property><property na"
  "me=\"n_columns\">3</property><property name=\"column_spacing\">6</prope"
  "rty><property name=\"row_spacing\">6</property><child><object class=\"G"
  "tkLabel\" id=\"label_dl1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"xalign\">0<"
  "/property><property name=\"label\" translatable=\"yes\">_Download limit"
  ":</property><property name=\"use_underline\">True</property><property n"
  "ame=\"selectable\">True</property><property name=\"mnemonic_widget\">sp"
  "inbutton_dl</property></object><packing><property name=\"x_options\">GT"
  "K_FILL</property></packing></child><child><object class=\"GtkLabel\" id"
  "=\"label_ul1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"xalign\">0</property><p"
  "roperty name=\"label\" translatable=\"yes\">_Upload limit:</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"selectab"
  "le\">True</property><property name=\"mnemonic_widget\">spinbutton_ul</p"
  "roperty></object><packing><property name=\"top_attach\">1</property><pr"
  "operty name=\"bottom_attach\">2</property><property name=\"x_options\">"
  "GTK_FILL</property></packing></child><child><object class=\"GtkSpinButt"
  "on\" id=\"spinbutton_dl1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"invisible_ch"
  "ar\">\342\200\242</property><property name=\"width_chars\">8</property>"
  "<property name=\"primary_icon_activatable\">False</property><property n"
  "ame=\"secondary_icon_activatable\">False</property><property name=\"pri"
  "mary_icon_sensitive\">True</property><property name=\"secondary_icon_se"
  "nsitive\">True</property><property name=\"update_policy\">if-valid</pro"
  "perty></object><packing><property name=\"left_attach\">1</property><pro"
  "perty name=\"right_attach\">2</property><property name=\"x_options\">GT"
  "K_FILL</property><property name=\"y_options\">GTK_FILL</property></pack"
  "ing></child><child><object class=\"GtkSpinButton\" id=\"spinbutton_ul1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"invisible_char\">\342\200\242</propert"
  "y><property name=\"width_chars\">8</property><property name=\"primary_i"
  "con_activatable\">False</property><property name=\"secondary_icon_activ"
  "atable\">False</property><property name=\"primary_icon_sensitive\">True"
  "</property><property name=\"secondary_icon_sensitive\">True</property><"
  "property name=\"update_policy\">if-valid</property></object><packing><p"
  "roperty name=\"left_attach\">1</property><property name=\"right_attach\""
  ">2</property><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property><property name=\"x_options\">GTK_FILL</prop"
  "erty><property name=\"y_options\">GTK_FILL</property></packing></child>"
  "<child><object class=\"GtkLabel\" id=\"label_dl_kb1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">kB/s</property></object><packing><property name=\"left_atta"
  "ch\">2</property><property name=\"right_attach\">3</property></packing>"
  "</child><child><object class=\"GtkLabel\" id=\"label_ul_kb1\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"xalign\">0</property><property name=\"label\" t"
  "ranslatable=\"yes\">kB/s</property></object><packing><property name=\"l"
  "eft_attach\">2</property><property name=\"right_attach\">3</property><p"
  "roperty name=\"top_attach\">1</property><property name=\"bottom_attach\""
  ">2</property></packing></child></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "VBox\" id=\"vbox9\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkHBox\" id"
  "=\"hbox8\"><property name=\"sensitive\">False</property><property name="
  "\"can_focus\">False</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkLabel\" id=\"label_proxy\"><property name=\"sen"
  "sitive\">False</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">(TODO) _Proxy address:</property><property name=\"use_under"
  "line\">True</property><property name=\"selectable\">True</property><pro"
  "perty name=\"mnemonic_widget\">entry_proxy_ip</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkEntry\" id=\"entry_proxy_ip\"><property name="
  "\"sensitive\">False</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"invisible_char\">\342\200\242</property><property n"
  "ame=\"invisible_char_set\">True</property><property name=\"primary_icon"
  "_activatable\">False</property><property name=\"secondary_icon_activata"
  "ble\">False</property><property name=\"primary_icon_sensitive\">True</p"
  "roperty><property name=\"secondary_icon_sensitive\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"label_proxy_port\"><pro"
  "perty name=\"sensitive\">False</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">:</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">2</property><"
  "/packing></child><child><object class=\"GtkEntry\" id=\"entry_proxy_por"
  "t\"><property name=\"sensitive\">False</property><property name=\"can_f"
  "ocus\">True</property><property name=\"max_length\">5</property><proper"
  "ty name=\"invisible_char\">\342\200\242</property><property name=\"widt"
  "h_chars\">5</property><property name=\"invisible_char_set\">True</prope"
  "rty><property name=\"primary_icon_activatable\">False</property><proper"
  "ty name=\"secondary_icon_activatable\">False</property><property name=\""
  "primary_icon_sensitive\">True</property><property name=\"secondary_icon"
  "_sensitive\">True</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">3</property></packing></child></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkLabel\" id=\"label_proxy_msg\"><property name=\"sensitive\">F"
  "alse</property><property name=\"can_focus\">False</property><property n"
  "ame=\"xalign\">0</property><property name=\"xpad\">40</property><proper"
  "ty name=\"label\" translatable=\"yes\">&lt;i&gt;(leave blank to not use"
  " any VPN)&lt;/i&gt;</property><property name=\"use_markup\">True</prope"
  "rty></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">2</property></packing></child><child><o"
  "bject class=\"GtkCheckButton\" id=\"isolate_dbus_check\"><property name"
  "=\"label\" translatable=\"yes\">Isolate D_Bus session from system</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">False</property"
  "><property name=\"use_underline\">True</property><property name=\"activ"
  "e\">True</property><property name=\"draw_indicator\">True</property></o"
  "bject><packing><property name=\"expand\">True</property><property name="
  "\"fill\">True</property><property name=\"position\">3</property></packi"
  "ng></child></object></child></object></child><child type=\"label\"><obj"
  "ect class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">&lt;b&gt;Network Options&lt;/b&gt;</propert"
  "y><property name=\"use_markup\">True</property></object></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child><child><object class=\"GtkFrame\" id=\"frame_fs\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label_xalign\">0</property><property name=\"shadow_"
  "type\">none</property><child><object class=\"GtkAlignment\" id=\"alignm"
  "ent5\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"border_width\">6</property><pro"
  "perty name=\"bottom_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkVBox\" id=\"vbox5\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><child><object class=\"GtkCheckButton\" id=\"overlay_fs_check\">"
  "<property name=\"label\" translatable=\"yes\">_Keep file creations and "
  "modifications private to the sandbox</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"use_underli"
  "ne\">True</property><property name=\"image_position\">bottom</property>"
  "<property name=\"active\">True</property><property name=\"draw_indicato"
  "r\">True</property></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "label4\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"xalign\">0</property><propert"
  "y name=\"xpad\">40</property><property name=\"label\" translatable=\"ye"
  "s\">&lt;i&gt;(files will be saved in ~/Sandboxes/&amp;lt;sandbox name&a"
  "mp;gt;)&lt;/i&gt;</property><property name=\"use_markup\">True</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkAlignment\" id=\"alignment_ov"
  "erlay_fs_check\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"border_width\">6</pro"
  "perty><property name=\"left_padding\">12</property><child><object class"
  "=\"GtkVBox\" id=\"vbox6\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><child><object class=\"GtkChe"
  "ckButton\" id=\"overlay_fs_private_home_check\"><property name=\"label\""
  " translatable=\"yes\">Use a private _Home directory</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkLabel\" id=\"label"
  "8\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"xalign\">0</property><property nam"
  "e=\"xpad\">40</property><property name=\"label\" translatable=\"yes\">&"
  "lt;i&gt;(files in the system\'s Home will be invisible inside the sandb"
  "ox)&lt;/i&gt;</property><property name=\"use_markup\">True</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">2</property></packing></child></object></child></object></ch"
  "ild><child type=\"label\"><object class=\"GtkLabel\" id=\"label7\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;File"
  "system Options&lt;/b&gt;</property><property name=\"use_markup\">True</"
  "property></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">2</property></packing></child><child><object class=\"GtkFram"
  "e\" id=\"frame_other\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label_xalign\">"
  "0</property><property name=\"shadow_type\">none</property><child><objec"
  "t class=\"GtkAlignment\" id=\"alignment4\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"border_width\">6</property><property name=\"bottom_padding\">6</pr"
  "operty><property name=\"left_padding\">12</property><child><object clas"
  "s=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"spacing\">6"
  "</property><child><object class=\"GtkCheckButton\" id=\"disable_sound_c"
  "heck\"><property name=\"label\" translatable=\"yes\">Disable Pulse_Audi"
  "o sound</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"use_underline\">True</property><property"
  " name=\"image_position\">bottom</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label10\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"xalign\">0</property><pr"
  "operty name=\"label\" translatable=\"yes\">&lt;i&gt;(does not work if y"
  "ou use ALSA rather than PulseAudio)&lt;/i&gt;</property><property name="
  "\"use_markup\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">1</property></packing></child></object></child></object"
  "></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label12\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">&lt;b&gt"
  ";Other&lt;/b&gt;</property><property name=\"use_markup\">True</property"
  "></object></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">3</property></packing></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child></object></child><action"
  "-widgets><action-widget response=\"0\">close-button</action-widget><act"
  "ion-widget response=\"0\">button1</action-widget></action-widgets></obj"
  "ect><object class=\"GtkVBox\" id=\"firejail_settings_embed\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Alignment\" id=\"firejail_settings_run_alignment\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"border_width\">6</property><child><object class=\"GtkVBox\""
  " id=\"vbox7\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkVBox\" id=\"profile_vbox\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"spacing\">6</property><child><object class=\"GtkLabel\" id"
  "=\"profile_use_label\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"xalign\">0</pro"
  "perty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Firejail s"
  "ecurity profile&lt;/b&gt;</property><property name=\"use_markup\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkAlignment\" id=\"pr"
  "ofile_alignment\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"border_width\">6</pr"
  "operty><property name=\"left_padding\">12</property><child><object clas"
  "s=\"GtkComboBox\" id=\"profile_combobox\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"model\">profile-list-store</property></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"position\">1</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkVBox\" id=\"net_vbox\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkLabel\" id=\"net_label\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Net"
  "work options&lt;/b&gt;</property><property name=\"use_markup\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkAlignment\" id=\"net_a"
  "lignment\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"border_width\">6</property>"
  "<property name=\"left_padding\">12</property><child><object class=\"Gtk"
  "VBox\" id=\"vbox1\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkCheckButton\" id=\"enable_network_check_e"
  "mbed\"><property name=\"label\" translatable=\"yes\">_Enable network ac"
  "cess</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"active\">True</property><property name=\"draw_indicator\">True</pr"
  "operty></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkAlignment\" id=\"net_ali"
  "gnment_options\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"border_width\">6</pro"
  "perty><property name=\"left_padding\">12</property><child><object class"
  "=\"GtkTable\" id=\"table2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"n_rows\">2"
  "</property><property name=\"n_columns\">3</property><property name=\"co"
  "lumn_spacing\">6</property><property name=\"row_spacing\">6</property><"
  "child><object class=\"GtkLabel\" id=\"label_dl\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">_Download limit:</property><property name=\"use_underline\">True<"
  "/property><property name=\"selectable\">True</property><property name=\""
  "mnemonic_widget\">spinbutton_dl</property></object><packing><property n"
  "ame=\"x_options\">GTK_FILL</property></packing></child><child><object c"
  "lass=\"GtkLabel\" id=\"label_ul\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"xali"
  "gn\">0</property><property name=\"label\" translatable=\"yes\">_Upload "
  "limit:</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"selectable\">True</property><property name=\"mnemonic_widget"
  "\">spinbutton_ul</property></object><packing><property name=\"top_attac"
  "h\">1</property><property name=\"bottom_attach\">2</property><property "
  "name=\"x_options\">GTK_FILL</property></packing></child><child><object "
  "class=\"GtkSpinButton\" id=\"spinbutton_dl\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"invisible_char\">\342\200\242</property><property name=\"width_ch"
  "ars\">8</property><property name=\"primary_icon_activatable\">False</pr"
  "operty><property name=\"secondary_icon_activatable\">False</property><p"
  "roperty name=\"primary_icon_sensitive\">True</property><property name=\""
  "secondary_icon_sensitive\">True</property><property name=\"update_polic"
  "y\">if-valid</property></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"right_attach\">2</property><property name"
  "=\"x_options\">GTK_FILL</property><property name=\"y_options\">GTK_FILL"
  "</property></packing></child><child><object class=\"GtkSpinButton\" id="
  "\"spinbutton_ul\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"invisible_char\">\342"
  "\200\242</property><property name=\"width_chars\">8</property><property"
  " name=\"primary_icon_activatable\">False</property><property name=\"sec"
  "ondary_icon_activatable\">False</property><property name=\"primary_icon"
  "_sensitive\">True</property><property name=\"secondary_icon_sensitive\""
  ">True</property><property name=\"update_policy\">if-valid</property></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"right_attach\">2</property><property name=\"top_attach\">1</propert"
  "y><property name=\"bottom_attach\">2</property><property name=\"x_optio"
  "ns\">GTK_FILL</property><property name=\"y_options\">GTK_FILL</property"
  "></packing></child><child><object class=\"GtkLabel\" id=\"label_dl_kb\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">kB/s</property></object><packing><property"
  " name=\"left_attach\">2</property><property name=\"right_attach\">3</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label_u"
  "l_kb\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">kB/s</property></object><packing><p"
  "roperty name=\"left_attach\">2</property><property name=\"right_attach\""
  ">3</property><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property></packing></child></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">1</property></packing></child><child><object cl"
  "ass=\"GtkVBox\" id=\"filesystem_vbox\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkLabel\" id=\"filesystem"
  "_label\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"xalign\">0</property><propert"
  "y name=\"label\" translatable=\"yes\">&lt;b&gt;Security level of Home d"
  "irectory&lt;/b&gt;</property><property name=\"use_markup\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkAlignment\" id=\"filesyste"
  "m_alignment\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"border_width\">6</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkTable\" id=\"table_fs_privs\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"n_row"
  "s\">8</property><property name=\"n_columns\">6</property><property name"
  "=\"homogeneous\">True</property><child><object class=\"GtkLabel\" id=\""
  "label_mod\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"tooltip_text\" translatabl"
  "e=\"yes\">This app can modify existing documents in your Home.</propert"
  "y><property name=\"xalign\">0</property><property name=\"label\" transl"
  "atable=\"yes\">Modify or delete files in your Home</property><property "
  "name=\"wrap\">True</property></object><packing><property name=\"right_a"
  "ttach\">3</property><property name=\"top_attach\">2</property><property"
  " name=\"bottom_attach\">3</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"label_create\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"t"
  "ooltip_text\" translatable=\"yes\">This app can create new documents in"
  " your Home, which will be visible by other apps.</property><property na"
  "me=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">Create files in your Home</property><property name=\"wrap\">True</prop"
  "erty><property name=\"width_chars\">40</property></object><packing><pro"
  "perty name=\"right_attach\">3</property><property name=\"top_attach\">3"
  "</property><property name=\"bottom_attach\">4</property></packing></chi"
  "ld><child><object class=\"GtkLabel\" id=\"label_can\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">&lt;b&gt;This app can:&lt;/b&gt;</property><property name=\""
  "use_markup\">True</property></object><packing><property name=\"right_at"
  "tach\">3</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"label_read\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">This app can read the documents created by other apps i"
  "n your Home folder.</property><property name=\"xalign\">0</property><pr"
  "operty name=\"label\" translatable=\"yes\">Read files in your Home</pro"
  "perty><property name=\"wrap\">True</property></object><packing><propert"
  "y name=\"right_attach\">3</property><property name=\"top_attach\">1</pr"
  "operty><property name=\"bottom_attach\">2</property></packing></child><"
  "child><object class=\"GtkRadioButton\" id=\"fs_home_full\"><property na"
  "me=\"label\" translatable=\"yes\">Full access</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"ac"
  "tive\">True</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"left_attach\">3</property><property "
  "name=\"right_attach\">4</property></packing></child><child><object clas"
  "s=\"GtkImage\" id=\"image_read_priv\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_"
  "MASK</property><property name=\"stock\">gtk-no</property></object><pack"
  "ing><property name=\"left_attach\">5</property><property name=\"right_a"
  "ttach\">6</property><property name=\"top_attach\">1</property><property"
  " name=\"bottom_attach\">2</property></packing></child><child><object cl"
  "ass=\"GtkImage\" id=\"image_mod_priv\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_"
  "MASK</property><property name=\"stock\">gtk-no</property></object><pack"
  "ing><property name=\"left_attach\">5</property><property name=\"right_a"
  "ttach\">6</property><property name=\"top_attach\">2</property><property"
  " name=\"bottom_attach\">3</property></packing></child><child><object cl"
  "ass=\"GtkImage\" id=\"image_create_priv\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCT"
  "URE_MASK</property><property name=\"stock\">gtk-no</property></object><"
  "packing><property name=\"left_attach\">5</property><property name=\"rig"
  "ht_attach\">6</property><property name=\"top_attach\">3</property><prop"
  "erty name=\"bottom_attach\">4</property></packing></child><child><objec"
  "t class=\"GtkImage\" id=\"image_overlay_priv1\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_"
  "STRUCTURE_MASK</property><property name=\"stock\">gtk-yes</property></o"
  "bject><packing><property name=\"left_attach\">5</property><property nam"
  "e=\"right_attach\">6</property><property name=\"top_attach\">4</propert"
  "y><property name=\"bottom_attach\">5</property></packing></child><child"
  "><object class=\"GtkImage\" id=\"image_overlay_priv2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK "
  "| GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-no</propert"
  "y></object><packing><property name=\"left_attach\">5</property><propert"
  "y name=\"right_attach\">6</property><property name=\"top_attach\">5</pr"
  "operty><property name=\"bottom_attach\">6</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"label_overlay1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"tooltip_text\" translatable=\"yes\">This app can create"
  " new documents, which will only be visible inside the sandbox for this "
  "app. Other apps won\'t see the new files in your Home.</property><prope"
  "rty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">Create private files</property></object><packing><property name=\""
  "right_attach\">3</property><property name=\"top_attach\">4</property><p"
  "roperty name=\"bottom_attach\">5</property></packing></child><child><ob"
  "ject class=\"GtkLabel\" id=\"label_overlay2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">This app can modify existing"
  " documents, and the changes will only be visible inside the sandbox for"
  " this app. Other apps won\'t see the changes in your Home.</property><p"
  "roperty name=\"xalign\">0</property><property name=\"label\" translatab"
  "le=\"yes\">Make private copies of files in your Home\n&lt;small&gt;&lt;"
  "i&gt;(other apps can\'t see changes to the copies)&lt;/i&gt;&lt;/small&"
  "gt;</property><property name=\"use_markup\">True</property><property na"
  "me=\"wrap\">True</property><property name=\"width_chars\">40</property>"
  "</object><packing><property name=\"right_attach\">3</property><property"
  " name=\"top_attach\">5</property><property name=\"bottom_attach\">6</pr"
  "operty></packing></child><child><object class=\"GtkHSeparator\" id=\"hs"
  "eparator2\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property></object><packing><property name=\"right_at"
  "tach\">6</property><property name=\"top_attach\">6</property><property "
  "name=\"bottom_attach\">7</property></packing></child><child><object cla"
  "ss=\"GtkAlignment\" id=\"alignment_disposable\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"left_padding\">20</property><child><object class=\"GtkCheckBu"
  "tton\" id=\"fs_disposable_check\"><property name=\"label\" translatable"
  "=\"yes\">Use a disposable Home. Changes made to files will be deleted w"
  "hen the app is shut down</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"draw_indicator\">True</"
  "property></object></child></object><packing><property name=\"right_atta"
  "ch\">6</property><property name=\"top_attach\">7</property><property na"
  "me=\"bottom_attach\">8</property></packing></child><child><object class"
  "=\"GtkRadioButton\" id=\"fs_home_priv\"><property name=\"label\" transl"
  "atable=\"yes\">Private Home</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"draw_indicator\">Tru"
  "e</property><property name=\"group\">fs_home_full</property></object><p"
  "acking><property name=\"left_attach\">5</property><property name=\"righ"
  "t_attach\">6</property></packing></child><child><object class=\"GtkRadi"
  "oButton\" id=\"fs_home_ro\"><property name=\"label\" translatable=\"yes"
  "\">Read-only</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"draw_indicator\">True</property><pr"
  "operty name=\"group\">fs_home_full</property></object><packing><propert"
  "y name=\"left_attach\">4</property><property name=\"right_attach\">5</p"
  "roperty></packing></child><child><object class=\"GtkImage\" id=\"image_"
  "overlay_ro2\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"events\">GDK_ENTER_NOTIF"
  "Y_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property"
  " name=\"stock\">gtk-yes</property></object><packing><property name=\"le"
  "ft_attach\">4</property><property name=\"right_attach\">5</property><pr"
  "operty name=\"top_attach\">5</property><property name=\"bottom_attach\""
  ">6</property></packing></child><child><object class=\"GtkImage\" id=\"i"
  "mage_overlay_ro1\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"events\">GDK_ENTER_"
  "NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><pro"
  "perty name=\"stock\">gtk-yes</property></object><packing><property name"
  "=\"left_attach\">4</property><property name=\"right_attach\">5</propert"
  "y><property name=\"top_attach\">4</property><property name=\"bottom_att"
  "ach\">5</property></packing></child><child><object class=\"GtkImage\" i"
  "d=\"image_overlay_full2\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"events\">GDK"
  "_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</proper"
  "ty><property name=\"stock\">gtk-no</property></object><packing><propert"
  "y name=\"left_attach\">3</property><property name=\"right_attach\">4</p"
  "roperty><property name=\"top_attach\">5</property><property name=\"bott"
  "om_attach\">6</property></packing></child><child><object class=\"GtkIma"
  "ge\" id=\"image_create_ro\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"events\">G"
  "DK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</prop"
  "erty><property name=\"stock\">gtk-no</property></object><packing><prope"
  "rty name=\"left_attach\">4</property><property name=\"right_attach\">5<"
  "/property><property name=\"top_attach\">3</property><property name=\"bo"
  "ttom_attach\">4</property></packing></child><child><object class=\"GtkI"
  "mage\" id=\"image_mod_ro\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"events\">GD"
  "K_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</prope"
  "rty><property name=\"stock\">gtk-no</property></object><packing><proper"
  "ty name=\"left_attach\">4</property><property name=\"right_attach\">5</"
  "property><property name=\"top_attach\">2</property><property name=\"bot"
  "tom_attach\">3</property></packing></child><child><object class=\"GtkIm"
  "age\" id=\"image_read_ro\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"events\">GD"
  "K_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</prope"
  "rty><property name=\"stock\">gtk-yes</property></object><packing><prope"
  "rty name=\"left_attach\">4</property><property name=\"right_attach\">5<"
  "/property><property name=\"top_attach\">1</property><property name=\"bo"
  "ttom_attach\">2</property></packing></child><child><object class=\"GtkI"
  "mage\" id=\"image_read_full\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"events\""
  ">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</pr"
  "operty><property name=\"stock\">gtk-yes</property></object><packing><pr"
  "operty name=\"left_attach\">3</property><property name=\"right_attach\""
  ">4</property><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property></packing></child><child><object class=\"Gt"
  "kImage\" id=\"image_mod_full\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"events\""
  ">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</pr"
  "operty><property name=\"stock\">gtk-yes</property></object><packing><pr"
  "operty name=\"left_attach\">3</property><property name=\"right_attach\""
  ">4</property><property name=\"top_attach\">2</property><property name=\""
  "bottom_attach\">3</property></packing></child><child><object class=\"Gt"
  "kImage\" id=\"image_create_full\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"even"
  "ts\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK"
  "</property><property name=\"stock\">gtk-yes</property></object><packing"
  "><property name=\"left_attach\">3</property><property name=\"right_atta"
  "ch\">4</property><property name=\"top_attach\">3</property><property na"
  "me=\"bottom_attach\">4</property></packing></child><child><object class"
  "=\"GtkImage\" id=\"image_overlay_full1\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTU"
  "RE_MASK</property><property name=\"stock\">gtk-no</property></object><p"
  "acking><property name=\"left_attach\">3</property><property name=\"righ"
  "t_attach\">4</property><property name=\"top_attach\">4</property><prope"
  "rty name=\"bottom_attach\">5</property></packing></child></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">2</property></packing></child><child><object class=\"GtkVBox\" id=\""
  "sync_folder_vbox\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"spacing\">6</proper"
  "ty><child><object class=\"GtkLabel\" id=\"sync_folder_label\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"xalign\">0</property><property name=\"label\" t"
  "ranslatable=\"yes\">&lt;b&gt;Synchronise the following directories with"
  " the rest of the system&lt;/b&gt;</property><property name=\"use_markup"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkAlignment\""
  " id=\"sync_folder_alignment\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"border_w"
  "idth\">6</property><property name=\"left_padding\">12</property><child>"
  "<object class=\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkViewport\" id=\"viewpor"
  "t1\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><child><object class=\"GtkTreeView\" id=\"sync_fol"
  "der_tree_view\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"has_tooltip\">True</pro"
  "perty><property name=\"model\">sync-folder-name-store</property><proper"
  "ty name=\"headers_visible\">False</property><property name=\"enable_sea"
  "rch\">False</property><property name=\"search_column\">0</property><pro"
  "perty name=\"tooltip_column\">3</property></object></child></object><pa"
  "cking><property name=\"expand\">True</property><property name=\"fill\">"
  "True</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkVButtonBox\" id=\"sync_folder_button_box\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"layout_style\">start</property><child>"
  "<object class=\"GtkButton\" id=\"sync_folder_add_btn\"><property name=\""
  "label\">gtk-add</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">True</property><property name=\"use_stock\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">0</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"sync_folder_remove_bt"
  "n\"><property name=\"label\">gtk-remove</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"use_stock"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">1</property></packing></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">1</property></packing></child></object></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">3</p"
  "roperty></packing></child></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkAlignment\" id=\"firejail_advanced_alignment\"><property n"
  "ame=\"can_focus\">False</property><property name=\"xalign\">1</property"
  "><property name=\"xscale\">0</property><property name=\"bottom_padding\""
  ">6</property><property name=\"left_padding\">12</property><property nam"
  "e=\"right_padding\">12</property><child><object class=\"GtkButton\" id="
  "\"firejail_advanced_btn\"><property name=\"label\" translatable=\"yes\""
  ">_Advanced Settings</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">True</property><property name=\"image\">image-preferences2</p"
  "roperty><property name=\"use_underline\">True</property></object></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">1</property>"
  "</packing></child></object><object class=\"GtkCheckButton\" id=\"fireja"
  "il_settings_run\"><property name=\"label\" translatable=\"yes\">Run thi"
  "s application in a Firejail sandbox</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><object class=\"GtkImage\" id=\"image-preferences\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"stock\">gtk-preferences</property></object><object c"
  "lass=\"GtkImage\" id=\"image-preferences1\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"stock\">gtk-preferences</property></object><object class=\"GtkIma"
  "ge\" id=\"image-preferences2\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"stock\""
  ">gtk-preferences</property></object><object class=\"GtkListStore\" id=\""
  "profile-list-store\"><columns><column type=\"gchararray\"/><column type"
  "=\"gchararray\"/><column type=\"PangoStyle\"/></columns></object><objec"
  "t class=\"GtkListStore\" id=\"sync-folder-name-store\"><columns><column"
  " type=\"gchararray\"/><column type=\"gboolean\"/><column type=\"gcharar"
  "ray\"/><column type=\"gchararray\"/></columns></object></interface>"
};

static const unsigned xfce_firejail_widget_ui_length = 48619u;

