/* automatically generated from xfce-firejail-widget.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce_firejail_widget_ui)
#endif
#ifdef __GNUC__
static const char xfce_firejail_widget_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce_firejail_widget_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkAdjustment\" id=\"filesystem_"
  "security_adjustment\"><property name=\"upper\">5</property><property na"
  "me=\"step_increment\">1</property><property name=\"page_increment\">5</"
  "property><property name=\"page_size\">1</property></object><object clas"
  "s=\"XfceTitledDialog\" id=\"firejail_settings_advanced\"><property name"
  "=\"can_focus\">False</property><property name=\"title\" translatable=\""
  "yes\">Advanced Security Settings</property><property name=\"default_wid"
  "th\">550</property><property name=\"default_height\">600</property><pro"
  "perty name=\"icon_name\">firejail-protect</property><property name=\"ty"
  "pe_hint\">normal</property><property name=\"subtitle\" translatable=\"y"
  "es\">Configure how Firejail runs your application in a sandbox</propert"
  "y><child internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-"
  "vbox1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"spacing\">2</property><child i"
  "nternal-child=\"action_area\"><object class=\"GtkHButtonBox\" id=\"dial"
  "og-action_area1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"layout_style\">start"
  "</property><child><object class=\"GtkButton\" id=\"close-button\"><prop"
  "erty name=\"label\">gtk-apply</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"use_stock\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty><property name=\"secondary\">True</property></packing></child><chi"
  "ld><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">"
  "gtk-cancel</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"use_stock\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"pack_type\">end</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkVBox\" id=\"vbox2\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkFrame\" id=\"frame_other"
  "1\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment1\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"border_width\""
  ">6</property><property name=\"bottom_padding\">6</property><property na"
  "me=\"left_padding\">12</property><child><object class=\"GtkCheckButton\""
  " id=\"firejail_settings_run1\"><property name=\"label\" translatable=\""
  "yes\">Run in a Firejail sandbox</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t></child></object></child><child type=\"label\"><object class=\"GtkLab"
  "el\" id=\"label2\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">&lt;b&gt;General&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property></object></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">0</property></packing></child><child><object cla"
  "ss=\"GtkFrame\" id=\"frame_net\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "_xalign\">0</property><property name=\"shadow_type\">none</property><ch"
  "ild><object class=\"GtkAlignment\" id=\"alignment3\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"border_width\">6</property><property name=\"bottom_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkCheckButton\" id=\"enabl"
  "e_network_check\"><property name=\"label\" translatable=\"yes\">_Enable"
  " network</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"active\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkCheckButton\" id=\"n"
  "et_auto_check\"><property name=\"label\" translatable=\"yes\">Fine-tune"
  "d _network control (can reduce performance)</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"active\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child><child><obj"
  "ect class=\"GtkAlignment\" id=\"alignment_net_auto_check\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"bottom_padding\">6</property><property name=\"left"
  "_padding\">12</property><child><object class=\"GtkVBox\" id=\"vbox3\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkTable\" id=\"table1\"><property name=\"visible\">True</propert"
  "y><property name=\"sensitive\">False</property><property name=\"can_foc"
  "us\">False</property><property name=\"n_rows\">2</property><property na"
  "me=\"n_columns\">3</property><property name=\"column_spacing\">6</prope"
  "rty><property name=\"row_spacing\">6</property><child><object class=\"G"
  "tkLabel\" id=\"label_dl\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"xalign\">0</"
  "property><property name=\"label\" translatable=\"yes\">_Download limit:"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"selectable\">True</property><property name=\"mnemonic_widget\">spi"
  "nbutton_dl</property></object><packing><property name=\"x_options\">GTK"
  "_FILL</property></packing></child><child><object class=\"GtkLabel\" id="
  "\"label_ul\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"xalign\">0</property><prop"
  "erty name=\"label\" translatable=\"yes\">_Upload limit:</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"selectable\""
  ">True</property><property name=\"mnemonic_widget\">spinbutton_ul</prope"
  "rty></object><packing><property name=\"top_attach\">1</property><proper"
  "ty name=\"bottom_attach\">2</property><property name=\"x_options\">GTK_"
  "FILL</property></packing></child><child><object class=\"GtkSpinButton\""
  " id=\"spinbutton_dl\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"invisible_char\">"
  "\342\200\242</property><property name=\"width_chars\">8</property><prop"
  "erty name=\"primary_icon_activatable\">False</property><property name=\""
  "secondary_icon_activatable\">False</property><property name=\"primary_i"
  "con_sensitive\">True</property><property name=\"secondary_icon_sensitiv"
  "e\">True</property><property name=\"update_policy\">if-valid</property>"
  "</object><packing><property name=\"left_attach\">1</property><property "
  "name=\"right_attach\">2</property><property name=\"x_options\">GTK_FILL"
  "</property><property name=\"y_options\">GTK_FILL</property></packing></"
  "child><child><object class=\"GtkSpinButton\" id=\"spinbutton_ul\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"invisible_char\">\342\200\242</property><pro"
  "perty name=\"width_chars\">8</property><property name=\"primary_icon_ac"
  "tivatable\">False</property><property name=\"secondary_icon_activatable"
  "\">False</property><property name=\"primary_icon_sensitive\">True</prop"
  "erty><property name=\"secondary_icon_sensitive\">True</property><proper"
  "ty name=\"update_policy\">if-valid</property></object><packing><propert"
  "y name=\"left_attach\">1</property><property name=\"right_attach\">2</p"
  "roperty><property name=\"top_attach\">1</property><property name=\"bott"
  "om_attach\">2</property><property name=\"x_options\">GTK_FILL</property"
  "><property name=\"y_options\">GTK_FILL</property></packing></child><chi"
  "ld><object class=\"GtkLabel\" id=\"label_dl_kb\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">kB/s</property></object><packing><property name=\"left_attach\">2"
  "</property><property name=\"right_attach\">3</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label_ul_kb\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">kB/s</property></object><packing><property name=\"left_atta"
  "ch\">2</property><property name=\"right_attach\">3</property><property "
  "name=\"top_attach\">1</property><property name=\"bottom_attach\">2</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">0</property></packing></child><child><object class=\"GtkVBox\" "
  "id=\"vbox9\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><child><object class=\"GtkHBox\" id=\"hbox8"
  "\"><property name=\"sensitive\">False</property><property name=\"can_fo"
  "cus\">False</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkLabel\" id=\"label_proxy\"><property name=\"sensitive\""
  ">False</property><property name=\"can_focus\">False</property><property"
  " name=\"xalign\">0</property><property name=\"label\" translatable=\"ye"
  "s\">(TODO) _Proxy address:</property><property name=\"use_underline\">T"
  "rue</property><property name=\"selectable\">True</property><property na"
  "me=\"mnemonic_widget\">entry_proxy_ip</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkEntry\" id=\"entry_proxy_ip\"><property name=\"sensit"
  "ive\">False</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"invisible_char\">\342\200\242</property><property name=\"in"
  "visible_char_set\">True</property><property name=\"primary_icon_activat"
  "able\">False</property><property name=\"secondary_icon_activatable\">Fa"
  "lse</property><property name=\"primary_icon_sensitive\">True</property>"
  "<property name=\"secondary_icon_sensitive\">True</property></object><pa"
  "cking><property name=\"expand\">True</property><property name=\"fill\">"
  "True</property><property name=\"position\">1</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label_proxy_port\"><property n"
  "ame=\"sensitive\">False</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">:</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child><child><object class=\"GtkEntry\" id=\"entry_proxy_port\"><pro"
  "perty name=\"sensitive\">False</property><property name=\"can_focus\">T"
  "rue</property><property name=\"max_length\">5</property><property name="
  "\"invisible_char\">\342\200\242</property><property name=\"width_chars\""
  ">5</property><property name=\"invisible_char_set\">True</property><prop"
  "erty name=\"primary_icon_activatable\">False</property><property name=\""
  "secondary_icon_activatable\">False</property><property name=\"primary_i"
  "con_sensitive\">True</property><property name=\"secondary_icon_sensitiv"
  "e\">True</property></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">3</property></packing></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"label_proxy_msg\"><property name=\"sensitive\">False</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"xa"
  "lign\">0</property><property name=\"xpad\">40</property><property name="
  "\"label\" translatable=\"yes\">&lt;i&gt;(leave blank to not use any VPN"
  ")&lt;/i&gt;</property><property name=\"use_markup\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child></object></child></object><packing><property nam"
  "e=\"expand\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">2</property></packing></child><child><object cl"
  "ass=\"GtkCheckButton\" id=\"isolate_dbus_check\"><property name=\"label"
  "\" translatable=\"yes\">Isolate D_Bus session from system</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"active\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">3</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">&lt;b&gt;Network Options&lt;/b&gt;</property><prope"
  "rty name=\"use_markup\">True</property></object></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">1</property></packing></child>"
  "<child><object class=\"GtkFrame\" id=\"frame_fs\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label_xalign\">0</property><property name=\"shadow_type\">n"
  "one</property><child><object class=\"GtkAlignment\" id=\"alignment5\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"border_width\">6</property><property na"
  "me=\"bottom_padding\">6</property><property name=\"left_padding\">12</p"
  "roperty><child><object class=\"GtkVBox\" id=\"vbox5\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "child><object class=\"GtkCheckButton\" id=\"overlay_fs_check\"><propert"
  "y name=\"label\" translatable=\"yes\">_Keep file creations and modifica"
  "tions private to the sandbox</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"image_position\">bottom</property><propert"
  "y name=\"active\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label4\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"xalign\">0</property><property name=\""
  "xpad\">40</property><property name=\"label\" translatable=\"yes\">&lt;i"
  "&gt;(files will be saved in ~/Sandboxes/&amp;lt;sandbox name&amp;gt;)&l"
  "t;/i&gt;</property><property name=\"use_markup\">True</property></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child><child><object class=\"GtkAlignment\" id=\"alignment_overlay_fs_"
  "check\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">6</property><pr"
  "operty name=\"left_padding\">12</property><child><object class=\"GtkVBo"
  "x\" id=\"vbox6\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><child><object class=\"GtkCheckButton\""
  " id=\"overlay_fs_private_home_check\"><property name=\"label\" translat"
  "able=\"yes\">Use a private _Home directory</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"use_u"
  "nderline\">True</property><property name=\"draw_indicator\">True</prope"
  "rty></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkLabel\" id=\"label8\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"xalign\">0</property><property name=\"xpad\""
  ">40</property><property name=\"label\" translatable=\"yes\">&lt;i&gt;(f"
  "iles in the system\'s Home will be invisible inside the sandbox)&lt;/i&"
  "gt;</property><property name=\"use_markup\">True</property></object><pa"
  "cking><property name=\"expand\">True</property><property name=\"fill\">"
  "True</property><property name=\"position\">1</property></packing></chil"
  "d></object></child></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">2</property></packing></child></object></child></object></child><chi"
  "ld type=\"label\"><object class=\"GtkLabel\" id=\"label7\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Filesystem O"
  "ptions&lt;/b&gt;</property><property name=\"use_markup\">True</property"
  "></object></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">2</property></packing></child><child><object class=\"GtkFrame\" id=\""
  "frame_other\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label_xalign\">0</proper"
  "ty><property name=\"shadow_type\">none</property><child><object class=\""
  "GtkAlignment\" id=\"alignment4\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"borde"
  "r_width\">6</property><property name=\"bottom_padding\">6</property><pr"
  "operty name=\"left_padding\">12</property><child><object class=\"GtkHBo"
  "x\" id=\"hbox1\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkCheckButton\" id=\"disable_sound_check\"><pr"
  "operty name=\"label\" translatable=\"yes\">Disable Pulse_Audio sound</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"im"
  "age_position\">bottom</property><property name=\"draw_indicator\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkLabel\" id=\"label1"
  "0\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"xalign\">0</property><property nam"
  "e=\"label\" translatable=\"yes\">&lt;i&gt;(does not work if you use ALS"
  "A rather than PulseAudio)&lt;/i&gt;</property><property name=\"use_mark"
  "up\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">1</property></packing></child></object></child></object></child><"
  "child type=\"label\"><object class=\"GtkLabel\" id=\"label12\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Other&lt"
  ";/b&gt;</property><property name=\"use_markup\">True</property></object"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">3</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object></child><action-widgets>"
  "<action-widget response=\"0\">close-button</action-widget><action-widge"
  "t response=\"0\">button1</action-widget></action-widgets></object><obje"
  "ct class=\"GtkVBox\" id=\"firejail_settings_embed\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"spacing\">6</property><child><object class=\"GtkAlignment"
  "\" id=\"firejail_settings_run_alignment\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><child><object class=\"GtkVBox\" id=\"vb"
  "ox7\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkVBox\" id=\"profile_vbox\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"profi"
  "le_use_label\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"xalign\">0</property><p"
  "roperty name=\"label\" translatable=\"yes\">&lt;b&gt;Firejail security "
  "profile&lt;/b&gt;</property><property name=\"use_markup\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkAlignment\" id=\"profile_al"
  "ignment\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"border_width\">6</property><"
  "property name=\"left_padding\">12</property><child><object class=\"GtkC"
  "omboBox\" id=\"profile_combobox\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"mode"
  "l\">profile-list-store</property></object></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">1</property></packing></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkVBox\" id=\"net_vbox\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkLab"
  "el\" id=\"net_label\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"xalign\">0</prop"
  "erty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Network opt"
  "ions&lt;/b&gt;</property><property name=\"use_markup\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkAlignment\" id=\"net_alignment"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"border_width\">6</property><propert"
  "y name=\"left_padding\">12</property><child><object class=\"GtkCheckBut"
  "ton\" id=\"enable_network_check_embed\"><property name=\"label\" transl"
  "atable=\"yes\">_Enable network access</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"use_underl"
  "ine\">True</property><property name=\"active\">True</property><property"
  " name=\"draw_indicator\">True</property></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkVBox\" id=\"filesystem_vbox\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkLabel\" id=\"filesystem_label\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">&lt;b&gt;Security level of Home directory&lt;/b&gt;</property><propert"
  "y name=\"use_markup\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkAlignment\" id=\"filesystem_alignment\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkTable\" id=\"table_fs_privs\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"n_rows\">8</property><property name=\"n_col"
  "umns\">6</property><property name=\"homogeneous\">True</property><child"
  "><object class=\"GtkLabel\" id=\"label_mod\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">This app can modify existing"
  " documents in your Home.</property><property name=\"xalign\">0</propert"
  "y><property name=\"label\" translatable=\"yes\">Modify or delete files "
  "in your Home</property><property name=\"wrap\">True</property></object>"
  "<packing><property name=\"right_attach\">3</property><property name=\"t"
  "op_attach\">2</property><property name=\"bottom_attach\">3</property></"
  "packing></child><child><object class=\"GtkLabel\" id=\"label_create\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"tooltip_text\" translatable=\"yes\">Thi"
  "s app can create new documents in your Home, which will be visible by o"
  "ther apps.</property><property name=\"xalign\">0</property><property na"
  "me=\"label\" translatable=\"yes\">Create files in your Home</property><"
  "property name=\"wrap\">True</property><property name=\"width_chars\">40"
  "</property></object><packing><property name=\"right_attach\">3</propert"
  "y><property name=\"top_attach\">3</property><property name=\"bottom_att"
  "ach\">4</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label_can\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"xalign\">0</property><"
  "property name=\"label\" translatable=\"yes\">&lt;b&gt;This app can:&lt;"
  "/b&gt;</property><property name=\"use_markup\">True</property></object>"
  "<packing><property name=\"right_attach\">3</property></packing></child>"
  "<child><object class=\"GtkLabel\" id=\"label_read\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">This app can read the"
  " documents created by other apps in your Home folder.</property><proper"
  "ty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">Read files in your Home</property><property name=\"wrap\">True</p"
  "roperty></object><packing><property name=\"right_attach\">3</property><"
  "property name=\"top_attach\">1</property><property name=\"bottom_attach"
  "\">2</property></packing></child><child><object class=\"GtkRadioButton\""
  " id=\"fs_home_full\"><property name=\"label\" translatable=\"yes\">Full"
  " access</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"active\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"left"
  "_attach\">3</property><property name=\"right_attach\">4</property></pac"
  "king></child><child><object class=\"GtkImage\" id=\"image_read_priv\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LE"
  "AVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\""
  ">gtk-no</property></object><packing><property name=\"left_attach\">5</p"
  "roperty><property name=\"right_attach\">6</property><property name=\"to"
  "p_attach\">1</property><property name=\"bottom_attach\">2</property></p"
  "acking></child><child><object class=\"GtkImage\" id=\"image_mod_priv\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_L"
  "EAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\""
  ">gtk-no</property></object><packing><property name=\"left_attach\">5</p"
  "roperty><property name=\"right_attach\">6</property><property name=\"to"
  "p_attach\">2</property><property name=\"bottom_attach\">3</property></p"
  "acking></child><child><object class=\"GtkImage\" id=\"image_create_priv"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GD"
  "K_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property name=\"sto"
  "ck\">gtk-no</property></object><packing><property name=\"left_attach\">"
  "5</property><property name=\"right_attach\">6</property><property name="
  "\"top_attach\">3</property><property name=\"bottom_attach\">4</property"
  "></packing></child><child><object class=\"GtkImage\" id=\"image_overlay"
  "_priv1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"events\">GDK_ENTER_NOTIFY_MAS"
  "K | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property name"
  "=\"stock\">gtk-yes</property></object><packing><property name=\"left_at"
  "tach\">5</property><property name=\"right_attach\">6</property><propert"
  "y name=\"top_attach\">4</property><property name=\"bottom_attach\">5</p"
  "roperty></packing></child><child><object class=\"GtkImage\" id=\"image_"
  "overlay_priv2\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"events\">GDK_ENTER_NOT"
  "IFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><proper"
  "ty name=\"stock\">gtk-no</property></object><packing><property name=\"l"
  "eft_attach\">5</property><property name=\"right_attach\">6</property><p"
  "roperty name=\"top_attach\">5</property><property name=\"bottom_attach\""
  ">6</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel_overlay1\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">This app can create new documents, which will only be vis"
  "ible inside the sandbox for this app. Other apps won\'t see the new fil"
  "es in your Home.</property><property name=\"xalign\">0</property><prope"
  "rty name=\"label\" translatable=\"yes\">Create private files</property>"
  "</object><packing><property name=\"right_attach\">3</property><property"
  " name=\"top_attach\">4</property><property name=\"bottom_attach\">5</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label_o"
  "verlay2\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"tooltip_text\" translatable="
  "\"yes\">This app can modify existing documents, and the changes will on"
  "ly be visible inside the sandbox for this app. Other apps won\'t see th"
  "e changes in your Home.</property><property name=\"xalign\">0</property"
  "><property name=\"label\" translatable=\"yes\">Make private copies of f"
  "iles in your Home\n&lt;small&gt;&lt;i&gt;(other apps can\'t see changes"
  " to the copies)&lt;/i&gt;&lt;/small&gt;</property><property name=\"use_"
  "markup\">True</property><property name=\"wrap\">True</property><propert"
  "y name=\"width_chars\">40</property></object><packing><property name=\""
  "right_attach\">3</property><property name=\"top_attach\">5</property><p"
  "roperty name=\"bottom_attach\">6</property></packing></child><child><ob"
  "ject class=\"GtkHSeparator\" id=\"hseparator2\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property></objec"
  "t><packing><property name=\"right_attach\">6</property><property name=\""
  "top_attach\">6</property><property name=\"bottom_attach\">7</property><"
  "/packing></child><child><object class=\"GtkAlignment\" id=\"alignment_d"
  "isposable\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"left_padding\">20</propert"
  "y><child><object class=\"GtkCheckButton\" id=\"fs_disposable_check\"><p"
  "roperty name=\"label\" translatable=\"yes\">Use a disposable Home. Chan"
  "ges made to files will be deleted when the app is shut down</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"draw_indicator\">True</property></object></child></object><"
  "packing><property name=\"right_attach\">6</property><property name=\"to"
  "p_attach\">7</property><property name=\"bottom_attach\">8</property></p"
  "acking></child><child><object class=\"GtkRadioButton\" id=\"fs_home_pri"
  "v\"><property name=\"label\" translatable=\"yes\">Private Home</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"draw_indicator\">True</property><property name=\"group\">"
  "fs_home_full</property></object><packing><property name=\"left_attach\""
  ">5</property><property name=\"right_attach\">6</property></packing></ch"
  "ild><child><object class=\"GtkRadioButton\" id=\"fs_home_ro\"><property"
  " name=\"label\" translatable=\"yes\">Read-only</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">False</property><property name=\"d"
  "raw_indicator\">True</property><property name=\"group\">fs_home_full</p"
  "roperty></object><packing><property name=\"left_attach\">4</property><p"
  "roperty name=\"right_attach\">5</property></packing></child><child><obj"
  "ect class=\"GtkImage\" id=\"image_overlay_ro2\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_"
  "STRUCTURE_MASK</property><property name=\"stock\">gtk-yes</property></o"
  "bject><packing><property name=\"left_attach\">4</property><property nam"
  "e=\"right_attach\">5</property><property name=\"top_attach\">5</propert"
  "y><property name=\"bottom_attach\">6</property></packing></child><child"
  "><object class=\"GtkImage\" id=\"image_overlay_ro1\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK |"
  " GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-yes</propert"
  "y></object><packing><property name=\"left_attach\">4</property><propert"
  "y name=\"right_attach\">5</property><property name=\"top_attach\">4</pr"
  "operty><property name=\"bottom_attach\">5</property></packing></child><"
  "child><object class=\"GtkImage\" id=\"image_overlay_full2\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY"
  "_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-no</p"
  "roperty></object><packing><property name=\"left_attach\">3</property><p"
  "roperty name=\"right_attach\">4</property><property name=\"top_attach\""
  ">5</property><property name=\"bottom_attach\">6</property></packing></c"
  "hild><child><object class=\"GtkImage\" id=\"image_create_ro\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTI"
  "FY_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-no<"
  "/property></object><packing><property name=\"left_attach\">4</property>"
  "<property name=\"right_attach\">5</property><property name=\"top_attach"
  "\">3</property><property name=\"bottom_attach\">4</property></packing><"
  "/child><child><object class=\"GtkImage\" id=\"image_mod_ro\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIF"
  "Y_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-no</"
  "property></object><packing><property name=\"left_attach\">4</property><"
  "property name=\"right_attach\">5</property><property name=\"top_attach\""
  ">2</property><property name=\"bottom_attach\">3</property></packing></c"
  "hild><child><object class=\"GtkImage\" id=\"image_read_ro\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY"
  "_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-yes</"
  "property></object><packing><property name=\"left_attach\">4</property><"
  "property name=\"right_attach\">5</property><property name=\"top_attach\""
  ">1</property><property name=\"bottom_attach\">2</property></packing></c"
  "hild><child><object class=\"GtkImage\" id=\"image_read_full\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTI"
  "FY_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-yes"
  "</property></object><packing><property name=\"left_attach\">3</property"
  "><property name=\"right_attach\">4</property><property name=\"top_attac"
  "h\">1</property><property name=\"bottom_attach\">2</property></packing>"
  "</child><child><object class=\"GtkImage\" id=\"image_mod_full\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NO"
  "TIFY_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">gtk-y"
  "es</property></object><packing><property name=\"left_attach\">3</proper"
  "ty><property name=\"right_attach\">4</property><property name=\"top_att"
  "ach\">2</property><property name=\"bottom_attach\">3</property></packin"
  "g></child><child><object class=\"GtkImage\" id=\"image_create_full\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"events\">GDK_ENTER_NOTIFY_MASK | GDK_LEA"
  "VE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property name=\"stock\">"
  "gtk-yes</property></object><packing><property name=\"left_attach\">3</p"
  "roperty><property name=\"right_attach\">4</property><property name=\"to"
  "p_attach\">3</property><property name=\"bottom_attach\">4</property></p"
  "acking></child><child><object class=\"GtkImage\" id=\"image_overlay_ful"
  "l1\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"events\">GDK_ENTER_NOTIFY_MASK | "
  "GDK_LEAVE_NOTIFY_MASK | GDK_STRUCTURE_MASK</property><property name=\"s"
  "tock\">gtk-no</property></object><packing><property name=\"left_attach\""
  ">3</property><property name=\"right_attach\">4</property><property name"
  "=\"top_attach\">4</property><property name=\"bottom_attach\">5</propert"
  "y></packing></child></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">1</property></packing></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">2</property></packing></child><chil"
  "d><object class=\"GtkVBox\" id=\"sync_folder_vbox\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"spacing\">6</property><child><object class=\"GtkLabel\" i"
  "d=\"sync_folder_label\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"xalign\">0</pr"
  "operty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Synchroni"
  "se the following directories with the rest of the system&lt;/b&gt;</pro"
  "perty><property name=\"use_markup\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkAlignment\" id=\"sync_folder_alignment\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"border_width\">6</property><property name=\"le"
  "ft_padding\">12</property><child><object class=\"GtkHBox\" id=\"hbox2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkViewport\" id=\"viewport1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><child><object c"
  "lass=\"GtkTreeView\" id=\"sync_folder_tree_view\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"has_tooltip\">True</property><property name=\"model\">sync-f"
  "older-name-store</property><property name=\"headers_visible\">False</pr"
  "operty><property name=\"enable_search\">False</property><property name="
  "\"search_column\">0</property><property name=\"tooltip_column\">3</prop"
  "erty></object></child></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkVButtonBo"
  "x\" id=\"sync_folder_button_box\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"layo"
  "ut_style\">start</property><child><object class=\"GtkButton\" id=\"sync"
  "_folder_add_btn\"><property name=\"label\">gtk-add</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"use_stock\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkB"
  "utton\" id=\"sync_folder_remove_btn\"><property name=\"label\">gtk-remo"
  "ve</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"use_stock\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">1</property></packing></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">1</property></pack"
  "ing></child></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">3</property></packing></child></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkAlignment\" id=\"firejail_"
  "advanced_alignment\"><property name=\"can_focus\">False</property><prop"
  "erty name=\"xalign\">1</property><property name=\"xscale\">0</property>"
  "<property name=\"bottom_padding\">6</property><property name=\"left_pad"
  "ding\">12</property><property name=\"right_padding\">12</property><chil"
  "d><object class=\"GtkButton\" id=\"firejail_advanced_btn\"><property na"
  "me=\"label\" translatable=\"yes\">_Advanced Settings</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"image\">image-preferences2</property><property name=\"use_underline"
  "\">True</property></object></child></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">1</property></packing></child></object><object cla"
  "ss=\"GtkCheckButton\" id=\"firejail_settings_run\"><property name=\"lab"
  "el\" translatable=\"yes\">Run this application in a Firejail sandbox</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"dr"
  "aw_indicator\">True</property></object><object class=\"GtkImage\" id=\""
  "image-preferences\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"stock\">gtk-prefer"
  "ences</property></object><object class=\"GtkImage\" id=\"image-preferen"
  "ces1\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"stock\">gtk-preferences</proper"
  "ty></object><object class=\"GtkImage\" id=\"image-preferences2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"stock\">gtk-preferences</property></object><"
  "object class=\"GtkListStore\" id=\"profile-list-store\"><columns><colum"
  "n type=\"gchararray\"/><column type=\"gchararray\"/><column type=\"Pang"
  "oStyle\"/></columns></object><object class=\"GtkListStore\" id=\"sync-f"
  "older-name-store\"><columns><column type=\"gchararray\"/><column type=\""
  "gboolean\"/><column type=\"gchararray\"/><column type=\"gchararray\"/><"
  "/columns></object></interface>"
};

static const unsigned xfce_firejail_widget_ui_length = 44324u;

